#!/usr/bin/env python3
"""
gen_table5.py: regenerate manuscript/tables/table5-governance-license.tex
from data/protocol-scores.yaml.

Table 5 expands the composite Axis 10 cell of Table 1 into its three
sub-fields: steward, license, and the ordinal observability score. It was
hand-authored until 2026-09-14, and it drifted:

  * ACP carried obs=1 against the YAML's 2, and LOKA obs=1 against the
    YAML's 3, so two of eight rows disagreed with Table 1;
  * AP2 carried an observability score, though the commerce-settlement
    protocols are explicitly not rubric scored (sec:rubric:limits) and
    appear in table2-commerce-stack.tex instead;
  * ACNBP was missing entirely, while sec:governance opens by arguing that
    ACNBP's technical strength is undercut by the absence of a formal SDO,
    a claim the table was supposed to evidence;
  * three stewards and two licenses disagreed with the YAML.

Membership uses the same layer filter as gen_table1.py, so the two tables
cannot disagree about which protocols are rubric scored.

Do NOT hand-edit table5-governance-license.tex; edit the YAML and rerun this.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing: install with: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "protocol-scores.yaml"
TEX_PATH = REPO / "manuscript" / "tables" / "table5-governance-license.tex"

# Layer 3 protocols are surveyed on the commerce stack, not this rubric.
EXCLUDED_LAYER = "commerce-settlement"

# Short labels, so the steward column gets the width. Same mapping as
# gen_table6.py.
PROTOCOL_HEADERS = {
    "a2a": "A2A",
    "mcp": "MCP",
    "acp": "ACP",
    "agntcy": "AGNTCY",
    "anp": "ANP",
    "coral": "Coral",
    "loka": "LOKA",
    "acnbp": "ACNBP",
}


def escape_latex(s: str) -> str:
    return s.replace("&", "\\&").replace("_", "\\_").replace("#", "\\#")


def rubric_protocols(scores: dict) -> list[tuple[str, dict]]:
    """Protocols scored against the 10-axis rubric (Layers 1 and 2)."""
    return [
        (pid, data)
        for pid, data in scores.items()
        if isinstance(data, dict) and data.get("layer") != EXCLUDED_LAYER
    ]


def render_row(pid: str, data: dict) -> str:
    gov = data.get("axis_10") or {}
    label = PROTOCOL_HEADERS.get(pid, pid.upper())
    steward = escape_latex(str(gov.get("governance", "?")))
    license_ = escape_latex(str(gov.get("license", "?")))
    obs = gov.get("observability", "?")
    return f"    {label} & {steward} & {license_} & {obs} \\\\"


def render_table(scores: dict) -> str:
    rows = rubric_protocols(scores)
    lines = [
        "% Generated by scripts/gen_table5.py: do NOT hand-edit.",
        "% Source: data/protocol-scores.yaml (axis_10 block).",
        "",
        "\\begin{table}[t]",
        "  \\centering",
        "  \\caption{Governance, licensing, and observability: the composite "
        "Axis 10 cell of Table~\\ref{tab:rubric-matrix} expanded into its three "
        "sub-fields. Steward and license are transcribed, not scored; only "
        "observability is ordinal, on the 0 to 3 anchors of "
        "\\S\\ref{sec:rubric:axis10}. The rows are the eight rubric-scored "
        "protocols; the five commerce-settlement protocols are not rubric "
        "scored (\\S\\ref{sec:rubric:limits}) and appear in "
        "Table~\\ref{tab:commerce-stack}.}",
        "  \\label{tab:governance-license}",
        "  \\footnotesize",
        "  \\begin{tabular}{@{}p{0.11\\textwidth}p{0.42\\textwidth}"
        "p{0.24\\textwidth}c@{}}",
        "    \\toprule",
        "    Protocol & Steward & License & Obs.\\ score \\\\",
        "    \\midrule",
    ]
    lines.extend(render_row(pid, data) for pid, data in rows)
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    scores = yaml.safe_load(YAML_PATH.read_text())
    if not isinstance(scores, dict):
        sys.exit(f"Unexpected YAML shape: {type(scores).__name__}")
    rows = rubric_protocols(scores)
    TEX_PATH.write_text(render_table(scores))
    print(f"Wrote {TEX_PATH.relative_to(REPO)} ({len(rows)} protocols)")
    for pid, data in rows:
        gov = data.get("axis_10") or {}
        print(f"  {PROTOCOL_HEADERS.get(pid, pid):<7} obs={gov.get('observability')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
