#!/usr/bin/env python3
"""
gen_table6.py: regenerate manuscript/tables/table6-severity-coverage.tex
from data/threat-coverage.yaml.

Table 6 is the severity-adjusted companion to Table 3 and to the Axis 8 count.
The count answers "how many of the twelve does the spec address?"; it cannot
answer "what is left unaddressed, weighted by how much each class matters?"
Two protocols with the same count can differ by an order of magnitude in
residual risk if one of them addressed the two cheapest classes.

Definitions, all of them declared in data/threat-coverage.yaml rather than here:
  * each threat class carries a band (critical / high / moderate) and an
    integer weight (3 / 2 / 1);
  * `na` cells are dropped from both numerator and denominator, so a protocol
    is not charged for a threat outside its structural scope;
  * only `addressed` counts in the numerator. `partial` counts as unaddressed,
    which is the same rule Axis 8 uses, so the two views cannot disagree.

Do NOT hand-edit table6-severity-coverage.tex; edit the YAML and rerun this.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing: install with: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "threat-coverage.yaml"
TEX_PATH = REPO / "manuscript" / "tables" / "table6-severity-coverage.tex"

PROTOCOL_HEADERS = {
    "a2a": "A2A",
    "mcp": "MCP",
    "acp": "ACP",
    "agntcy": "AGNTCY",
    "anp": "ANP",
    "coral": "Coral",
    "loka": "LOKA",
    "acnbp": "ACNBP",
}

BANDS = ("critical", "high", "moderate")


def rows(data: dict) -> list[dict]:
    severity = data["severity"]
    matrix = data["matrix"]
    out = []
    for proto in data["protocols"]:
        cells = matrix[proto]
        per_band = {b: [0, 0] for b in BANDS}  # [addressed, applicable]
        weight_hit = 0
        weight_applicable = 0
        residual_high = 0
        for threat, cell in cells.items():
            coverage = (cell or {}).get("coverage")
            if coverage == "na":
                continue
            band = severity[threat]["band"]
            weight = severity[threat]["weight"]
            per_band[band][1] += 1
            weight_applicable += weight
            if coverage == "addressed":
                per_band[band][0] += 1
                weight_hit += weight
            elif band in ("critical", "high"):
                residual_high += weight
        out.append(
            {
                "proto": proto,
                "count": per_band["critical"][0]
                + per_band["high"][0]
                + per_band["moderate"][0],
                "bands": per_band,
                "swc": 100.0 * weight_hit / weight_applicable,
                "weight_hit": weight_hit,
                "weight_applicable": weight_applicable,
                "residual": residual_high,
            }
        )
    return out


def render_table(data: dict) -> str:
    severity = data["severity"]
    band_totals = {
        b: sum(1 for s in severity.values() if s["band"] == b) for b in BANDS
    }
    total_weight = sum(s["weight"] for s in severity.values())
    computed = rows(data)

    lines = [
        "% Generated by scripts/gen_table6.py: do NOT hand-edit.",
        "% Source: data/threat-coverage.yaml (severity block).",
        "",
        "\\begin{table}[t]",
        "  \\centering",
        "  \\caption{Severity-adjusted threat coverage, the companion view to "
        "the Axis 8 count of Table~\\ref{tab:threat-surface}. Bands and integer "
        "weights are declared in the companion repository, not computed here: "
        f"{band_totals['critical']} critical classes at weight 3, "
        f"{band_totals['high']} high at weight 2, "
        f"{band_totals['moderate']} moderate at weight 1, for "
        f"{total_weight} points across the twelve. Band columns read "
        "\\emph{addressed / applicable}, where \\texttt{na} classes are "
        "excluded from both. SWC is severity-weighted coverage: addressed "
        "weight over applicable weight. Residual is the unaddressed weight in "
        "the critical and high bands only, counting \\texttt{partial} as "
        "unaddressed exactly as Axis 8 does. Higher SWC is better; lower "
        "residual is better.}",
        "  \\label{tab:severity-coverage}",
        "  \\footnotesize",
        "  \\begin{tabular}{lcccccr}",
        "    \\toprule",
        "    Protocol & Axis 8 & Crit. & High & Mod. & SWC & Resid. \\\\",
        "             & (of 12) & (w.\\ 3) & (w.\\ 2) & (w.\\ 1) & & \\\\",
        "    \\midrule",
    ]
    for r in computed:
        b = r["bands"]
        lines.append(
            "    %s & %d & %d/%d & %d/%d & %d/%d & %.0f\\%% & %d \\\\"
            % (
                PROTOCOL_HEADERS.get(r["proto"], r["proto"].upper()),
                r["count"],
                b["critical"][0],
                b["critical"][1],
                b["high"][0],
                b["high"][1],
                b["moderate"][0],
                b["moderate"][1],
                r["swc"],
                r["residual"],
            )
        )
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    data = yaml.safe_load(YAML_PATH.read_text())
    TEX_PATH.write_text(render_table(data))
    print(f"Wrote {TEX_PATH.relative_to(REPO)}")
    for r in rows(data):
        print(
            "  %-7s count %2d  weighted %2d/%2d = %3.0f%%  residual(crit+high) %2d"
            % (
                r["proto"],
                r["count"],
                r["weight_hit"],
                r["weight_applicable"],
                r["swc"],
                r["residual"],
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
