#!/usr/bin/env python3
"""
gen_table4.py: regenerate manuscript/tables/table4-industry-adoption.tex
from data/industry-adoption.yaml.

Emits a tabular with one row per vertical and one column per protocol family.
Each cell lists the named deployments with their status (GA / Pilot /
Announced). Empty cells render as `n/a`.

Do NOT hand-edit table4-industry-adoption.tex; edit the YAML and rerun this.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing: install with: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "industry-adoption.yaml"
TEX_PATH = REPO / "manuscript" / "tables" / "table4-industry-adoption.tex"

VERTICAL_LABELS = {
    "enterprise_saas":   "Enterprise SaaS",
    "commerce_payments": "Commerce \\& payments",
    "healthcare":        "Healthcare",
    "finance":           "Finance",
}

PROTOCOL_HEADERS = {
    "a2a":            "A2A",
    "mcp":            "MCP",
    "acp":            "ACP",
    "agntcy":         "AGNTCY",
    "commerce_stack": "Commerce stack",
}

STATUS_TAGS = {
    "ga":        "GA",
    "pilot":     "Pilot",
    "announced": "Ann.",
}


def escape_latex(s: str) -> str:
    return (s.replace("&", "\\&")
             .replace("_", "\\_")
             .replace("#", "\\#"))


def fmt_entries(entries: list[dict] | None) -> str:
    if not entries:
        return "n/a"
    parts = []
    for e in entries:
        vendor = escape_latex(e.get("vendor", "?"))
        status = STATUS_TAGS.get(e.get("status", ""), e.get("status", "?"))
        parts.append(f"{vendor} ({status})")
    return "\\scriptsize " + ", \\linebreak ".join(parts)


def render_table(data: dict) -> str:
    verticals = data["verticals"]
    protocols = data["protocols_compared"]
    matrix = data["matrix"]
    headers = [PROTOCOL_HEADERS.get(p, p.upper()) for p in protocols]

    col_spec = "p{2.3cm}" + "p{2.6cm}" * len(protocols)
    lines = [
        "% Generated by scripts/gen_table4.py: do NOT hand-edit.",
        "% Source: data/industry-adoption.yaml.",
        "",
        "\\begin{table*}[t]",
        "  \\centering",
        "  \\caption{Industry adoption by vertical at the 2026-Q1 cutoff. "
        "Cells list named production-or-pilot deployments with status: "
        "\\textit{GA} (generally available), \\textit{Pilot}, or "
        "\\textit{Ann.}\\ (announced). Status claims are Tier-4 "
        "(vendor blog) sourced; behavioural claims about deployments "
        "are not made in this table. The healthcare and finance "
        "verticals are under-populated because public disclosure is "
        "less common in those sectors.}",
        "  \\label{tab:industry-adoption}",
        "  \\footnotesize",
        f"  \\begin{{tabular}}{{{col_spec}}}",
        "    \\toprule",
        "    Vertical & " + " & ".join(headers) + " \\\\",
        "    \\midrule",
    ]
    for v in verticals:
        row = [VERTICAL_LABELS.get(v, v.replace("_", " ").title())]
        for p in protocols:
            entries = (matrix.get(v) or {}).get(p) or []
            row.append(fmt_entries(entries))
        lines.append("    " + " & ".join(row) + " \\\\[6pt]")
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table*}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    data = yaml.safe_load(YAML_PATH.read_text())
    rendered = render_table(data)
    TEX_PATH.write_text(rendered)
    n_cells = sum(
        len(matrix_v.get(p) or [])
        for matrix_v in data["matrix"].values()
        for p in data["protocols_compared"]
    )
    print(f"Wrote {TEX_PATH.relative_to(REPO)} "
          f"({len(data['verticals'])} verticals × "
          f"{len(data['protocols_compared'])} protocols, "
          f"{n_cells} populated entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
