#!/usr/bin/env python3
"""
gen_table1.py: regenerate manuscript/tables/table1-rubric-matrix.tex
from data/protocol-scores.yaml.

Reads the YAML, emits a longtable with one row per protocol and one column
per rubric axis. Cells encode ordinal scores (axes 1-3, 5-7, 9), the
threat-surface count (axis 8 as "N/12"), the transport tuple (axis 4 as
a short multi-line cell), and the governance triple (axis 10 as
"steward / license / obs"). Protocols with no scored axes ("TBD")
get a placeholder row.

Commerce-settlement entries (AP2, Visa TAP, Mastercard Agent Pay, ERC-8004)
are excluded: they are not scored against this rubric and appear instead in
table2-commerce-stack.tex. They carry `layer: commerce-settlement` in the
YAML so the taxonomy figure can still reference them.

Do NOT hand-edit table1-rubric-matrix.tex; edit the YAML and rerun this.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing: install with: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "protocol-scores.yaml"
TEX_PATH = REPO / "manuscript" / "tables" / "table1-rubric-matrix.tex"

# Ordinal axes vs. structural axes: drives cell formatting.
ORDINAL_AXES = {1, 2, 3, 5, 6, 7, 9}
THREAT_AXIS = 8           # rendered as "N/12"
TRANSPORT_AXIS = 4        # tuple: rendered as short multi-line
GOVERNANCE_AXIS = 10      # composite triple: rendered as "steward / license / obs"

# Layer 3 protocols are surveyed on the commerce stack, not this rubric.
EXCLUDED_LAYER = "commerce-settlement"


def fmt_ordinal(entry: dict | None) -> str:
    if not entry or "score" not in entry:
        return "n/a"
    s = entry["score"]
    if isinstance(s, str):
        return "TBD"
    return f"\\score{{{s}}}"


def fmt_threat(entry: dict | None) -> str:
    if not entry or "score" not in entry:
        return "n/a"
    s = entry["score"]
    if isinstance(s, str):
        return "TBD"
    return f"\\score{{{s}/12}}"


def fmt_transport(entry: dict | None) -> str:
    if not entry or "tuple" not in entry:
        return "n/a"
    t = entry["tuple"]
    transports = ", ".join(t.get("transports", []))[:30]
    return f"\\scriptsize {transports}"


def fmt_governance(entry: dict | None) -> str:
    if not entry:
        return "n/a"
    # Steward and license names are free text from the YAML and can contain
    # LaTeX specials ("LF AI & Data"). An unescaped & silently becomes a
    # column separator and breaks the row.
    steward = escape_latex(str(entry.get("governance", "?")))
    license_ = escape_latex(str(entry.get("license", "?")))
    obs = entry.get("observability", "?")
    return f"\\scriptsize {steward} / {license_} / obs={obs}"


def escape_latex(s: str) -> str:
    return s.replace("&", "\\&").replace("_", "\\_").replace("#", "\\#")


def render_row(protocol_id: str, data: dict, axes: range) -> str:
    name = escape_latex(data.get("name", protocol_id))
    cells = [f"\\textbf{{{name}}}"]
    for axis in axes:
        entry = data.get(f"axis_{axis}")
        if axis in ORDINAL_AXES:
            cells.append(fmt_ordinal(entry))
        elif axis == THREAT_AXIS:
            cells.append(fmt_threat(entry))
        elif axis == TRANSPORT_AXIS:
            cells.append(fmt_transport(entry))
        elif axis == GOVERNANCE_AXIS:
            cells.append(fmt_governance(entry))
    return " & ".join(cells) + " \\\\"


def rubric_protocols(scores: dict) -> list[tuple[str, dict]]:
    """Protocols scored against the 10-axis rubric (Layers 1 and 2)."""
    return [
        (pid, data)
        for pid, data in scores.items()
        if isinstance(data, dict) and data.get("layer") != EXCLUDED_LAYER
    ]


def render_table(scores: dict) -> str:
    rows = rubric_protocols(scores)
    lines = [
        "% Generated by scripts/gen_table1.py: do NOT hand-edit.",
        "% Source: data/protocol-scores.yaml.",
        "",
        "\\begin{table*}[t]",
        "  \\centering",
        "  \\caption{Master rubric matrix. Ordinal axes (A1 to A3, A5 to A7, A9) use anchored "
        "descriptors 0 to 3. Threat-surface (A8) is a count N/12. Transport (A4) is a tuple "
        "(serialization summarized). Governance (A10) is the composite triple "
        "\\textit{steward / license / observability}. Scores are not summed; see "
        "\\S\\ref{sec:rubric}.}",
        "  \\label{tab:rubric-matrix}",
        "  \\footnotesize",
        "  \\textit{Panel (a): axes A1 to A5}\\par\\smallskip",
        "  \\resizebox{\\textwidth}{!}{%",
        "  \\begin{tabular}{p{4.2cm}cccp{5.0cm}c}",
        "    \\toprule",
        "    Protocol & A1 & A2 & A3 & A4 & A5 \\\\",
        "    \\midrule",
    ]
    for pid, data in rows:
        lines.append("    " + render_row(pid, data, range(1, 6)))
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}%",
            "  }",
            "  \\par\\medskip",
            "  \\textit{Panel (b): axes A6 to A10}\\par\\smallskip",
            "  \\resizebox{\\textwidth}{!}{%",
            "  \\begin{tabular}{p{4.2cm}ccccp{6.0cm}}",
            "    \\toprule",
            "    Protocol & A6 & A7 & A8 & A9 & A10 \\\\",
            "    \\midrule",
        ]
    )
    for pid, data in rows:
        lines.append("    " + render_row(pid, data, range(6, 11)))
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}%",
            "  }",
            "\\end{table*}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    scores = yaml.safe_load(YAML_PATH.read_text())
    if not isinstance(scores, dict):
        sys.exit(f"Unexpected YAML shape: {type(scores).__name__}")
    rendered = render_table(scores)
    TEX_PATH.write_text(rendered)
    n = len(rubric_protocols(scores))
    print(f"Wrote {TEX_PATH.relative_to(REPO)} ({n} protocols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
