#!/usr/bin/env python3
"""
gen_table3.py: regenerate manuscript/tables/table3-threat-surface.tex
from data/threat-coverage.yaml.

Emits a tabular with one row per threat class and one column per protocol.
Cells encode coverage as a single-letter token:
  A = Addressed in spec
  P = Partial
  N = Not addressed
  - = N/A

Do NOT hand-edit table3-threat-surface.tex; edit the YAML and rerun this.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML missing: install with: pip install pyyaml")

REPO = Path(__file__).resolve().parent.parent
YAML_PATH = REPO / "data" / "threat-coverage.yaml"
TEX_PATH = REPO / "manuscript" / "tables" / "table3-threat-surface.tex"

THREATS = [
    ("prompt_injection_protocol_boundary", "Prompt injection (protocol boundary)"),
    ("agent_impersonation",                "Agent impersonation"),
    ("message_replay",                     "Message replay"),
    ("capability_escalation",              "Capability escalation"),
    ("delegation_token_theft",             "Delegation token theft"),
    ("registry_poisoning",                 "Registry poisoning"),
    ("agentcard_supply_chain",             "AgentCard supply-chain"),
    ("message_tampering",                  "Message tampering / MITM"),
    ("side_channel_privacy_leak",          "Side-channel privacy leak"),
    ("denial_of_service",                  "Denial of service"),
    ("cross_agent_privilege_confusion",    "Cross-agent privilege confusion"),
    ("audit_log_tampering",                "Audit-log tampering"),
]

COVERAGE_TOKEN = {
    "addressed":     "\\textbf{A}",
    "partial":       "P",
    "not_addressed": "N",
    "na":            "n/a",
}

PROTOCOL_HEADERS = {
    "a2a":    "A2A",
    "mcp":    "MCP",
    "acp":    "ACP",
    "agntcy": "AGNTCY",
    "anp":    "ANP",
    "coral":  "Coral",
    "loka":   "LOKA",
    "acnbp":  "ACNBP",
    "ap2":    "AP2",
}


def cell(coverage: str | None) -> str:
    if not coverage:
        return "n/a"
    return COVERAGE_TOKEN.get(coverage, "?")


def render_table(data: dict) -> str:
    protocols = data["protocols"]
    matrix = data["matrix"]
    headers = [PROTOCOL_HEADERS.get(p, p.upper()) for p in protocols]

    col_spec = "l" + "c" * len(protocols)
    lines = [
        "% Generated by scripts/gen_table3.py: do NOT hand-edit.",
        "% Source: data/threat-coverage.yaml.",
        "",
        "\\begin{table}[h!]",
        "  \\centering",
        "  \\caption{Threat-surface coverage matrix. Twelve threat classes (rows) "
        "$\\times$ eight protocols (cols). Cells: "
        "\\textbf{A} = Addressed at the spec level; "
        "P = Partial or non-normative; "
        "N = Not addressed; "
        "n/a = Not applicable. Every cell is scored against specification "
        "text. ACP and AGNTCY were rescored from primary sources in "
        "2026-Q3: ACP against its OpenAPI document, which declares no "
        "security schemes; AGNTCY across its SLIM, OASF, Directory, and "
        "identity specifications.}",
        "  \\label{tab:threat-surface}",
        "  \\footnotesize",
        f"  \\begin{{tabular}}{{{col_spec}}}",
        "    \\toprule",
        "    Threat class & " + " & ".join(headers) + " \\\\",
        "    \\midrule",
    ]
    for key, label in THREATS:
        row = [label]
        for p in protocols:
            entry = matrix.get(p) or {}
            cov = (entry.get(key) or {}).get("coverage") if isinstance(entry.get(key), dict) else None
            row.append(cell(cov))
        lines.append("    " + " & ".join(row) + " \\\\")
    lines.extend(
        [
            "    \\bottomrule",
            "  \\end{tabular}",
            "\\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    data = yaml.safe_load(YAML_PATH.read_text())
    rendered = render_table(data)
    TEX_PATH.write_text(rendered)
    print(f"Wrote {TEX_PATH.relative_to(REPO)} "
          f"({len(THREATS)} threats × {len(data['protocols'])} protocols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
